# Site settings
title: Tete Xiao
description:
  en: "This is an academic website for Tete Xiao to share his experiences, projects, publications and tech/non-tech posts. Tete Xiao is an undergraduate student at Peking University (PKU). His research interests lie in the field of Machine Learning and Computer Vison."
  cn: "这是肖特特的个人学术主页，用于分享他的个人经历，项目，学术论文，技术相关/不相关的博客。"
keywords:
  en: "Tete Xiao,Publications,Posts,Research,Deep Learning,Computer Vision,Natural Language Processing"
  cn: "肖特特,学术论文,博客,研究,深度学习,计算机视觉,自然语言处理"
background: /images/background/background-berkeley.jpg
deep_background: /images/background/background-berkeley.jpg

baseurl: ""
# the subpath of your site, e.g. /blog/
url: "https://tete-xiao.github.io"
# the base hostname & protocol for your sit

# Paginationœ
paginate: 6
paginate_path: "/posts/page/:num/"

# Build settings
markdown: kramdown

# permalink setting
permalink: pretty
# highlighter: rouge
highlighter: rouge

# Social media link for the site
social:
  twitter:    citations?user=U4RqBdAAAAAJ&hl=en
  github:     Tete-Xiao
  facebook:   jasonhsiao97
  linkedin:   tetexiao
  rss:        /feed.xml

# customized document resources
collections:
  projects:
    output: true

scss:
  sass_dir: _scss
  style: :compressed

plugins:
  ['jekyll-paginate', 'jekyll/scholar', 'jekyll-sitemap']
